"use client";

import { useEffect, useRef } from "react";
import type { ReactNode } from "react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { FaFacebookMessenger, FaInstagram, FaWhatsapp } from "react-icons/fa";
import { SiMeta, SiTelegram } from "react-icons/si";

gsap.registerPlugin(ScrollTrigger);

type Variant = "inbox" | "leads" | "broadcast" | "analytics" | "connect";

const pages: Record<Variant, { no: string; name: string; title: string; description: string; accent: string }> = {
  inbox: { no: "01", name: "Inbox", title: "Every conversation.\nNothing gets lost.", description: "Lluna brings WhatsApp, Instagram and Facebook messages into one intelligent workspace, understands context and surfaces the conversations that need your team.", accent: "Conversation → Context → Action" },
  leads: { no: "02", name: "Lead Intelligence", title: "See the signal.\nAct on the lead.", description: "Turn every conversation into a live intent signal. Score leads, understand why the score changed and focus your team on the people most likely to convert.", accent: "Signal → Score → Priority" },
  broadcast: { no: "03", name: "Broadcast", title: "Reach more people.\nDo less work.", description: "Launch approved WhatsApp campaigns, select the right audience and keep delivery, scheduling and history in one place.", accent: "Audience → Message → Outcome" },
  analytics: { no: "04", name: "Analytics", title: "See the work.\nProve the outcome.", description: "Track conversations, automation, hot leads, bookings, saved hours and performance in one clear business view.", accent: "Activity → Conversion → ROI" },
  connect: { no: "05", name: "Connect", title: "Keep the stack.\nAdd the intelligence.", description: "Connect WhatsApp Business, Telegram, Meta and operational tools so alerts, conversations and downstream actions move together.", accent: "Channels → AI → Systems" },
};

function ChannelIcon({ kind }: { kind: string }) {
  const icons: Record<string, ReactNode> = {
    WhatsApp: <FaWhatsapp />, Instagram: <FaInstagram />, Messenger: <FaFacebookMessenger />, Meta: <SiMeta />, Telegram: <SiTelegram />,
  };
  return <span className={`channel-icon ${kind.toLowerCase()}`}>{icons[kind]}</span>;
}

function Browser({ children, title }: { children: ReactNode; title: string }) {
  return <div className="browser"><div className="browser-top"><span className="dots"><i/><i/><i/></span><span>{title}</span><b>● LIVE</b></div>{children}</div>;
}

function InboxMock() {
  return <Browser title="Lluna / Intelligent Inbox"><div className="inbox-ui"><aside className="side"><strong>Lluna</strong><div className="search">⌕ Search conversations...</div>{["Inbox 74","Leads","Analytics","Connect"].map((x,i)=><div className={`side-row ${i===0?"active":""}`} key={x}>{x}</div>)}<div className="contacts">{[["AM","Ahmad Malik"],["SL","Sarah Lee"],["JW","James Wong"]].map(x=><div className="contact" key={x[1]}><span>{x[0]}</span><b>{x[1]}<small>WhatsApp · active now</small></b></div>)}</div></aside><section className="chat"><header><div><b>Ahmad Malik</b><small>WhatsApp · active now</small></div><strong>🔥 Hot lead</strong></header><div className="bubble in">Hi, is the Growth plan still available?</div><div className="thinking">● ● ● &nbsp; Lluna is understanding context</div><div className="bubble out">Yes — it’s available. I can help you choose the right option and get you booked.</div><div className="grounded">✓ Response grounded in business knowledge</div></section><aside className="intel"><small>LLUNA INTELLIGENCE</small><h3>Context understood</h3><p>Conversation history, knowledge and intent are being used to decide what happens next.</p><div className="score"><small>Intent score</small><strong>86</strong><div><i/></div></div><div className="intel-row">🔥 Hot lead<small>Pricing + booking intent</small></div><div className="intel-row">✓ Knowledge match<small>Growth Plan · Pricing</small></div></aside></div></Browser>;
}

function LeadsMock() {
  const cols = [["🔥 Hot", "369", "#ea5858"], ["🟡 Warm", "402", "#c89326"], ["🔵 Browsing", "1237", "#4b80ec"]];
  return <Browser title="Lluna / Lead Intelligence"><div className="lead-ui"><div className="mock-heading"><div><small>AI-CLASSIFIED PIPELINE</small><h3>Who needs attention now?</h3></div><span>30 days⌄</span></div><div className="lead-cols">{cols.map((c,i)=><div className="lead-col" key={c[0]}><header><b>{c[0]}</b><span>{c[1]}</span></header>{[["86","Ahmad Malik"],["72","Sarah Lee"],["51","Jonathan"]].map((r,j)=><article key={r[1]}><strong style={{color:c[2]}}>{i===0?r[0]:i===1?String(Number(r[0])-20):String(Number(r[0])-60)}</strong><div><b>{r[1]}</b><small>{i===0?"Asked price + requested date":i===1?"Interested · needs nurturing":"Early-stage information"}</small></div></article>)}</div>)}</div></div></Browser>;
}

function BroadcastMock() {
  return <Browser title="Lluna / Broadcast"><div className="broadcast-ui"><section className="broadcast-main"><small>1. SELECT TEMPLATE</small><h3>Choose an approved message</h3>{["stem_cells_promo","eecp_promo_with_image"].map((x,i)=><div className={`template ${i===0?"selected":""}`} key={x}><span>◯</span><div><b>{x}</b><small>Hello {'{name}'}! We’re celebrating our latest update 🎉</small></div><em>✓ Approved</em></div>)}<small>2. SELECT CONTACTS</small><h3>2,663 contacts available</h3><div className="search">⌕ Search by name or number...</div>{["Bill Adams","Ajay Dhar","thanga lathu"].map(x=><div className="b-contact" key={x}><span>{x.slice(0,2).toUpperCase()}</span><b>{x}<small>+60 12 345 6789</small></b><em>🔥</em></div>)}</section><aside className="phone-wrap"><small>PREVIEW</small><div className="phone"><b>WhatsApp Business</b><div className="phone-bubble">Hello! We’re celebrating our latest update 🎉</div><div className="phone-bubble purple">I’d like to know more.</div></div><button>Send to 2,663 contacts →</button></aside></div></Browser>;
}

function AnalyticsMock() {
  return <Browser title="Lluna / Analytics"><div className="analytics-ui"><div className="analytics-hero"><div><small>PERFORMANCE OVERVIEW</small><h3>61 Bookings · 214 Hot Leads</h3><span>2026-07-23 → 2026-08-21 · 55% automated</span></div><div className="hero-stats"><b>8%<small>CONVERSION</small></b><b>123h<small>HOURS SAVED</small></b><b>5799<small>FOLLOW-UPS</small></b></div></div><div className="metric-row">{[["730","Total Contacts"],["55%","Bot Automation"],["214","Hot Leads"],["61","Bookings"]].map(x=><div key={x[1]}><small>{x[1]}</small><strong>{x[0]}</strong></div>)}</div><div className="chart-area"><div><b>Messages per day</b><div className="bars">{Array.from({length:18}).map((_,i)=><i key={i} style={{height:`${35+(i*29)%115}px`}}/>)}</div></div><div className="breakdown"><b>Lead breakdown</b><p>🔥 Hot <strong>29%</strong></p><p>🟡 Warm <strong>24%</strong></p><p>🔵 Cold <strong>46%</strong></p></div></div></div></Browser>;
}

function ConnectMock() {
  const rows = [["WhatsApp Business","Meta WhatsApp Business API","WhatsApp","Connected"],["Telegram Alerts","Instant lead alerts","Telegram","Connected"],["Meta Ads","Track ads and conversions","Meta","Connected"],["Email Notifications","Hot lead notifications","Messenger","Coming soon"]];
  return <Browser title="Lluna / Connect"><div className="connect-ui"><div className="mock-heading"><div><small>INTEGRATIONS</small><h3>Connect your tools and services.</h3></div><span>3 connected</span></div>{rows.map(r=><div className="integration" key={r[0]}><ChannelIcon kind={r[2]}/><div><b>{r[0]}</b><small>{r[1]}</small></div><em className={r[3]==="Connected"?"connected":""}>{r[3]}</em><button>{r[3]==="Connected"?"Edit":"View"}</button></div>)}</div></Browser>;
}

function Mock({ variant }: { variant: Variant }) {
  if (variant === "inbox") return <InboxMock />;
  if (variant === "leads") return <LeadsMock />;
  if (variant === "broadcast") return <BroadcastMock />;
  if (variant === "analytics") return <AnalyticsMock />;
  return <ConnectMock />;
}

export default function ProductExperience({ variant }: { variant: Variant }) {
  const root = useRef<HTMLElement>(null);
  const data = pages[variant];
  const titles: Record<Variant, ReactNode> = {
    inbox: <>From first message<br/><span>to the right action.</span></>,
    leads: <>Turn conversation<br/><span>into priority.</span></>,
    broadcast: <>One campaign.<br/><span>Every contact.</span></>,
    analytics: <>From activity<br/><span>to business evidence.</span></>,
    connect: <>Connect the stack.<br/><span>Centralize intelligence.</span></>,
  };
  const steps: Record<Variant, string[]> = {
    inbox: ["Receive", "Understand", "Respond", "Escalate"],
    leads: ["Listen", "Score", "Prioritize", "Act"],
    broadcast: ["Select", "Approve", "Send", "Measure"],
    analytics: ["Capture", "Classify", "Measure", "Improve"],
    connect: ["Connect", "Route", "Intelligence", "Action"],
  };

  useEffect(() => {
    const ctx = gsap.context(() => {
      gsap.from(".product-nav", { y: -24, opacity: 0, duration: .7, ease: "power4.out" });
      gsap.from(".story-kicker", { y: 20, opacity: 0, duration: .6, delay: .1 });
      gsap.from(".story-line", { yPercent: 110, opacity: 0, duration: .9, stagger: .1, delay: .2, ease: "power4.out" });
      gsap.from(".story-copy,.story-visual", { y: 30, opacity: 0, duration: .8, stagger: .12, delay: .4, ease: "power3.out" });
      gsap.to(".story-visual", { y: -45, rotateY: 0, scrollTrigger: { trigger: ".story-hero", start: "top top", end: "+=700", scrub: true } });
      gsap.to(".status-dot", { scale: 1.35, opacity: .5, duration: 1.1, repeat: -1, yoyo: true, ease: "sine.inOut" });
      gsap.utils.toArray<HTMLElement>(".reveal").forEach(el => gsap.from(el, { y: 55, opacity: 0, duration: .8, scrollTrigger: { trigger: el, start: "top 84%" } }));
    }, root);
    return () => ctx.revert();
  }, []);

  return <main ref={root} className="product-page">
    <style dangerouslySetInnerHTML={{__html: `
      @import url('https://fonts.googleapis.com/css2?family=Inter+Tight:wght@400;500;600;700&display=swap');
      *{box-sizing:border-box}.product-page{--bg:#f5f4f9;--ink:#10162d;--muted:#6f778d;--purple:#8052ff;min-height:100vh;background:var(--bg);color:var(--ink);font-family:'Inter Tight',system-ui,sans-serif;overflow:hidden}.product-page a{text-decoration:none;color:inherit}
      .product-nav{position:fixed;z-index:40;top:0;left:0;right:0;height:78px;padding:0 5vw;display:flex;align-items:center;justify-content:space-between;background:linear-gradient(180deg,#f5f4f9,rgba(245,244,249,.9),transparent);backdrop-filter:blur(10px)}.product-brand{display:flex;align-items:center;gap:10px;font-size:19px;font-weight:600}.product-brand i{width:31px;height:31px;display:grid;place-items:center;border-radius:10px;background:linear-gradient(135deg,#365cff,#a348ff);color:#fff;font-style:normal}.product-nav-mid{display:flex;gap:28px;color:#7f8799;font-size:12px}.product-nav-mid a:hover{color:var(--ink)}.product-demo{background:var(--ink);color:#fff;padding:11px 17px;border-radius:999px;font-size:11px}
      .story-hero{min-height:940px;padding:150px 6vw 95px;position:relative}.story-hero:after{content:'';position:absolute;left:0;right:0;bottom:0;height:1px;background:#dedee7}.story-hero-inner{max-width:1320px;margin:auto;display:grid;grid-template-columns:.82fr 1.18fr;gap:6vw;align-items:center}.story-kicker{display:flex;align-items:center;gap:10px;font-size:10px;letter-spacing:.2em;color:var(--purple);font-weight:700;text-transform:uppercase}.status-dot{width:7px;height:7px;border-radius:50%;background:#19bf67;box-shadow:0 0 0 6px #19bf6718}.story-title{font-size:clamp(62px,7.1vw,112px);line-height:.88;letter-spacing:-.075em;margin:27px 0 22px;font-weight:600}.story-title .soft,.process h2 span,.proof h2 span,.cta h2 span{color:#9aa0ad}.story-copy{max-width:510px;color:var(--muted);font-size:17px;line-height:1.62}.story-label{margin-top:24px;color:#8d95a5;font-size:10px;text-transform:uppercase;letter-spacing:.16em}.channel-row{display:flex;flex-wrap:wrap;gap:8px;margin-top:23px}.channel-pill{display:inline-flex;align-items:center;gap:8px;padding:7px 10px;border-radius:999px;background:#fff;border:1px solid #e3e2ea;font-size:9px;color:#687184;box-shadow:0 10px 25px #15132d09}.channel-icon{width:24px;height:24px;border-radius:50%;display:grid;place-items:center;color:#fff;font-size:12px}.channel-icon.whatsapp{background:#25d366}.channel-icon.instagram{background:linear-gradient(135deg,#feda75,#d62976,#4f5bd5)}.channel-icon.messenger{background:#1788ff}.channel-icon.meta{background:#111}.channel-icon.telegram{background:#2aabee}
      .story-visual{position:relative;transform:perspective(1600px) rotateY(-7deg) rotateX(2deg);transform-origin:center right;will-change:transform}.story-shadow{position:absolute;left:5%;right:5%;bottom:-30px;height:55px;border-radius:50%;background:#11132620;filter:blur(28px)}.browser{position:relative;background:#fff;border:1px solid #e3e3ea;border-radius:26px;overflow:hidden;box-shadow:0 50px 120px #17162820;z-index:2}.browser-top{height:53px;border-bottom:1px solid #ececf2;display:flex;align-items:center;gap:12px;padding:0 18px;color:#8991a2;font-size:10px}.dots{display:flex;gap:6px}.dots i{width:8px;height:8px;background:#d9d9e2;border-radius:50%}.browser-top b{margin-left:auto;color:#7845ef;background:#f1ecff;padding:7px 10px;border-radius:999px;font-size:8px}
      .inbox-ui{display:grid;grid-template-columns:24% 50% 26%;height:540px;background:#f5f6fa}.side{padding:16px 12px;background:#fff;border-right:1px solid #e7e7ee}.side>strong{display:block;font-size:12px;padding:3px 8px 15px}.search{height:31px;padding:9px;border-radius:8px;background:#f3f3f8;color:#9aa1af;font-size:8px;margin-bottom:8px}.side-row{height:31px;border-radius:8px;padding:8px;color:#7b8393;font-size:9px}.side-row.active{background:#8052ff;color:#fff}.contacts{margin-top:12px}.contact{display:flex;gap:8px;padding:11px 5px;border-top:1px solid #f0f0f4}.contact>span,.b-contact>span{width:27px;height:27px;border-radius:50%;display:grid;place-items:center;background:#19a78b;color:#fff;font-size:8px}.contact b,.b-contact b{font-size:9px}.contact small,.b-contact small{display:block;color:#969eac;font-size:7px;margin-top:3px;font-weight:400}.chat{padding:20px;background:#f5f5fa}.chat header{display:flex;align-items:center;justify-content:space-between}.chat header b{display:block;font-size:11px}.chat header small{display:block;font-size:7px;color:#9ba1ae;margin-top:3px}.chat header strong{font-size:8px;color:#e45a55;background:#fff0f1;border-radius:999px;padding:7px 9px}.bubble{max-width:73%;padding:13px 14px;border-radius:15px;margin-top:24px;font-size:9px;line-height:1.5}.bubble.in{background:#fff;border:1px solid #ececf1}.bubble.out{margin-left:auto;background:linear-gradient(135deg,#8052ff,#9a5eff);color:#fff}.thinking{display:inline-block;margin:12px 0;color:#7d55da;background:#eee9ff;padding:7px 9px;border-radius:999px;font-size:7px}.grounded{margin-top:17px;background:#ebfaf1;color:#2d975a;border-radius:10px;padding:9px;font-size:7px;text-align:center}.intel{padding:20px;background:#fff;border-left:1px solid #e7e7ee}.intel>small{font-size:7px;letter-spacing:.16em;color:#9ba1af}.intel h3{font-size:18px;margin:14px 0 7px}.intel p{font-size:8px;color:#7f8797;line-height:1.5}.score{margin-top:22px;padding:14px;border:1px solid #ece7f6;background:#fbfaff;border-radius:16px}.score small{display:block;color:#9aa1af;font-size:7px}.score strong{display:block;font-size:44px;letter-spacing:-.08em;margin:3px 0 8px}.score div{height:5px;border-radius:9px;background:#eeeaf5;overflow:hidden}.score i{display:block;width:86%;height:100%;background:linear-gradient(90deg,#8052ff,#b26dff)}.intel-row{padding:12px 0;border-bottom:1px solid #efeff3;font-size:8px}.intel-row small{display:block;color:#969daa;font-size:7px;margin-top:4px}
      .lead-ui,.broadcast-ui,.analytics-ui,.connect-ui{min-height:540px;background:#f5f6fa;padding:22px}.mock-heading{display:flex;align-items:end;justify-content:space-between;margin-bottom:18px}.mock-heading small{color:#9ba2b0;font-size:7px;letter-spacing:.14em}.mock-heading h3{margin:7px 0 0;font-size:19px}.mock-heading>span{background:#fff;border:1px solid #e4e4ea;border-radius:999px;padding:8px 11px;font-size:8px;color:#818a9b}.lead-cols{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.lead-col{background:#fff;border:1px solid #e4e4ea;border-radius:16px;padding:12px}.lead-col header{display:flex;justify-content:space-between;padding-bottom:12px;border-bottom:1px solid #ededf2;font-size:9px}.lead-col article{padding:15px 3px;border-bottom:1px solid #efeff3;display:grid;grid-template-columns:35px 1fr;gap:8px}.lead-col article strong{font-size:23px}.lead-col article b{font-size:9px}.lead-col article small{display:block;font-size:7px;color:#969daa;margin-top:3px}
      .broadcast-ui{display:grid;grid-template-columns:1.35fr .65fr}.broadcast-main{padding:2px 10px}.broadcast-main>small,.phone-wrap>small{font-size:7px;color:#9ca3b0;letter-spacing:.14em}.broadcast-main h3{font-size:12px;margin:5px 0 12px}.template{display:grid;grid-template-columns:20px 1fr auto;gap:9px;align-items:center;padding:13px 10px;background:#fff;border:1px solid #e5e5ec;border-radius:11px;margin-bottom:8px}.template.selected{border-color:#bca6ff;box-shadow:0 9px 25px #8052ff12}.template b{font-size:9px}.template small{display:block;color:#959dac;font-size:7px;line-height:1.4;margin-top:3px}.template em{font-style:normal;font-size:7px;color:#179953;background:#eaf8ef;padding:6px 7px;border-radius:999px}.b-contact{display:grid;grid-template-columns:28px 1fr auto;align-items:center;gap:9px;padding:9px 4px;border-bottom:1px solid #ececf2}.b-contact>span{background:#f06b6b}.b-contact em{font-style:normal}.phone-wrap{display:flex;flex-direction:column;align-items:center;justify-content:center;padding:10px;background:#fff}.phone{width:180px;background:#10131d;border-radius:26px;padding:10px;margin:10px 0}.phone>b{display:block;color:#fff;font-size:7px;padding:6px}.phone-bubble{max-width:87%;padding:9px;border-radius:12px;font-size:7px;line-height:1.45;margin-top:9px;background:#fff}.phone-bubble.purple{margin-left:auto;background:#8052ff;color:#fff}.phone-wrap button{width:90%;border:0;background:#8052ff;color:#fff;padding:10px;border-radius:10px;font-size:8px}
      .analytics-hero{display:flex;justify-content:space-between;align-items:center;background:linear-gradient(110deg,#7e49ff,#ff6d87);color:#fff;border-radius:18px;padding:20px}.analytics-hero small{font-size:7px;letter-spacing:.14em;opacity:.75}.analytics-hero h3{font-size:20px;margin:7px 0 3px}.analytics-hero span{font-size:8px;opacity:.76}.hero-stats{display:flex;gap:8px}.hero-stats b{min-width:70px;text-align:center;font-size:17px;padding:11px;border-radius:12px;background:#ffffff18}.hero-stats small{display:block;font-size:6px;margin-top:4px}.metric-row{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:10px}.metric-row div{padding:14px;background:#fff;border:1px solid #e5e5ec;border-radius:12px}.metric-row small{display:block;color:#8f96a4;font-size:7px}.metric-row strong{display:block;font-size:30px;margin-top:5px}.chart-area{display:grid;grid-template-columns:1.6fr .8fr;gap:9px;margin-top:10px}.chart-area>div,.breakdown{background:#fff;border:1px solid #e5e5ec;border-radius:12px;padding:14px}.chart-area b,.breakdown>b{font-size:9px}.bars{height:180px;margin-top:18px;display:flex;align-items:end;gap:6px;border-bottom:1px solid #e4e4ea}.bars i{flex:1;max-width:20px;border-radius:5px 5px 0 0;background:linear-gradient(180deg,#9c77ff,#d5c7ff)}.breakdown p{font-size:8px;padding:12px 0;border-bottom:1px solid #eee}.breakdown p strong{float:right}
      .connect-ui{padding:22px}.integration{display:grid;grid-template-columns:34px 1fr auto auto;align-items:center;gap:11px;background:#fff;border:1px solid #e5e5ec;border-radius:14px;padding:13px;margin-bottom:8px}.integration>div b{display:block;font-size:9px}.integration>div small{display:block;color:#929aaa;font-size:7px;margin-top:3px}.integration>em{font-style:normal;font-size:7px;color:#9aa1af}.integration>em.connected{color:#179353;background:#eaf8ef;padding:5px 7px;border-radius:999px}.integration button{border:1px solid #e3e3ea;background:#fff;border-radius:7px;padding:6px 8px;font-size:7px;color:#747e8f}
      .process{padding:125px 7vw;background:#fff}.process-inner,.proof-inner{max-width:1260px;margin:auto}.section-kicker{font-size:10px;letter-spacing:.2em;color:var(--purple);font-weight:700;text-transform:uppercase}.process h2,.proof h2,.cta h2{font-size:clamp(50px,6.5vw,92px);line-height:.92;letter-spacing:-.07em;margin:20px 0}.process-copy,.proof p{max-width:590px;color:var(--muted);font-size:17px;line-height:1.6}.process-track{display:grid;grid-template-columns:repeat(4,1fr);margin-top:75px;border-top:1px solid #dddde6}.process-node{padding:25px 18px;border-right:1px solid #dddde6;min-height:145px}.process-node b{color:#9a7cff;font-size:10px}.process-node strong{display:block;font-size:18px;margin:13px 0 8px}.process-node span{font-size:10px;color:#8b93a4;line-height:1.5}.proof{padding:125px 7vw;background:#11131f;color:#fff}.proof h2 span{color:#b991ff}.proof p{color:#b7bdc9}.proof-metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:35px;margin-top:70px}.proof-metric{border-top:1px solid #343746;padding-top:20px}.proof-metric strong{font-size:65px;letter-spacing:-.07em}.proof-metric strong span{font-size:24px;color:#b991ff}.proof-metric small{display:block;max-width:260px;color:#aab0bc;font-size:10px;line-height:1.5}.cta{padding:150px 7vw;background:#eeeaff;text-align:center}.cta h2{margin:22px 0}.cta p{max-width:520px;margin:0 auto 28px;color:#6f778d;font-size:16px;line-height:1.6}.cta a{display:inline-block;background:#10162d;color:#fff;padding:14px 22px;border-radius:999px;font-size:11px}.product-footer{padding:28px 7vw;background:#f5f4f9;display:flex;justify-content:space-between;color:#7f8799;font-size:10px}.product-footer span:last-child{display:flex;gap:18px}
      @media(max-width:900px){.product-nav-mid{display:none}.story-hero{padding-top:125px}.story-hero-inner{grid-template-columns:1fr}.story-title{font-size:64px}.story-visual{transform:none}.browser{margin-top:30px}.inbox-ui{height:480px}.intel{display:none}.inbox-ui{grid-template-columns:30% 70%}.lead-cols{gap:6px}.analytics-hero{display:block}.hero-stats{margin-top:12px}.proof-metrics,.process-track{grid-template-columns:1fr 1fr}.product-footer{display:block}.product-footer span:last-child{margin-top:15px;flex-wrap:wrap}}
      @media(max-width:600px){.product-demo{display:none}.story-hero{padding-left:20px;padding-right:20px}.story-title{font-size:54px}.process,.proof,.cta{padding:90px 20px}.broadcast-ui{grid-template-columns:1fr}.phone-wrap{display:none}.lead-cols{grid-template-columns:1fr}.lead-col:not(:first-child){display:none}.metric-row{grid-template-columns:1fr 1fr}.chart-area{grid-template-columns:1fr}.proof-metrics,.process-track{grid-template-columns:1fr}.product-footer{padding:25px 20px}.side{display:none}.inbox-ui{grid-template-columns:1fr}.chat{min-width:0}}
    `}} />
    <nav className="product-nav"><a href="/" className="product-brand"><i>L</i>Lluna</a><div className="product-nav-mid"><a href="/inbox">Product</a><a href="/leads">Intelligence</a><a href="/analytics">Results</a></div><a className="product-demo" href="/#demo">Book a demo ↗</a></nav>
    <section className="story-hero"><div className="story-hero-inner"><div className="story-copy"><div className="story-kicker"><span className="status-dot"/>{data.no} — {data.name}</div><h1 className="story-title"><span className="story-line">{data.title.split("\n")[0]}</span><span className="story-line soft">{data.title.split("\n")[1]}</span></h1><p>{data.description}</p><div className="story-label">{data.accent}</div><div className="channel-row"><div className="channel-pill"><ChannelIcon kind="WhatsApp"/>WhatsApp</div><div className="channel-pill"><ChannelIcon kind="Instagram"/>Instagram</div><div className="channel-pill"><ChannelIcon kind="Messenger"/>Messenger</div><div className="channel-pill"><ChannelIcon kind="Meta"/>Meta Ads</div></div></div><div className="story-visual"><Mock variant={variant}/><div className="story-shadow"/></div></div></section>
    <section className="process reveal"><div className="process-inner"><div className="section-kicker">HOW IT WORKS</div><h2>{titles[variant]}</h2><p className="process-copy">{data.description}</p><div className="process-track">{steps[variant].map((step,i)=><div className="process-node" key={step}><b>0{i+1}</b><strong>{step}</strong><span>{i===0?"Capture what is happening.":i===1?"Let AI understand the signal.":i===2?"Turn intelligence into a decision.":"Move the business forward."}</span></div>)}</div></div></section>
    <section className="proof reveal"><div className="proof-inner"><div className="section-kicker">MEASURABLE IMPACT</div><h2>Less manual work.<br/><span>More business happening.</span></h2><p>Lluna connects conversations, intelligence and action so your team can respond faster, qualify better and see the business outcome behind every interaction.</p><div className="proof-metrics"><div className="proof-metric"><strong>80<span>%</span></strong><small>Example automation potential across routine conversations.</small></div><div className="proof-metric"><strong>86<span>/100</span></strong><small>Example high-intent lead score surfaced by Lluna.</small></div><div className="proof-metric"><strong>1<span> workspace</span></strong><small>One place for the conversation and the business signal behind it.</small></div></div></div></section>
    <section className="cta"><div className="section-kicker">SEE LLUNA IN ACTION</div><h2>Build a better<br/><span>customer journey.</span></h2><p>Move from disconnected messages and manual work to one intelligent workflow your team can see and measure.</p><a href="/#demo">Book a Lluna demo ↗</a></section>
    <footer className="product-footer"><span>Lluna · AI-powered customer conversations.</span><span><a href="/">Home</a><a href="/inbox">Inbox</a><a href="/leads">Leads</a><a href="/broadcast">Broadcast</a><a href="/analytics">Analytics</a><a href="/connect">Connect</a></span></footer>
  </main>;
}
